# Generated by Django 3.1.1 on 2021-03-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
                ('translate', models.CharField(max_length=50)),
            ],
        ),
    ]
