# Generated by Django 3.1.1 on 2021-03-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='words',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
